"""
shared/event_schema.py

THE canonical InteractionEvent contract for CDaaS.

Every honeypot -> Agent -> Controller message uses this exact shape.
This file is frozen on Day 1 and only changes with a team conversation --
three other people's code depends on it staying stable.

Owner: whole team (decided together). Do not edit alone.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enums -- the fixed vocabulary every module agrees on
# ---------------------------------------------------------------------------

class Service(str, Enum):
    """Which honeypot type produced this event. Matches the four node types."""
    SSH = "ssh"
    WEB = "web"
    API = "api"
    DB = "db"


class EventType(str, Enum):
    """
    What kind of interaction this is. Keep this list short and general --
    add a new value only when an existing one genuinely doesn't fit,
    and only after the whole team agrees (this enum is imported everywhere).
    """
    CONNECTION = "connection"           # attacker opened a session
    AUTH_ATTEMPT = "auth_attempt"       # login/credential attempt (any service)
    COMMAND = "command"                 # shell command run (SSH)
    HTTP_REQUEST = "http_request"       # request to the Web node
    API_CALL = "api_call"               # call to the API node
    DB_QUERY = "db_query"               # query against the DB node
    FILE_ACCESS = "file_access"         # file read/download/upload attempt
    SCAN_DETECTED = "scan_detected"     # recon pattern (e.g. rapid port/endpoint probing)
    DISCONNECTION = "disconnection"     # attacker closed the session


# ---------------------------------------------------------------------------
# The event itself
# ---------------------------------------------------------------------------

class InteractionEvent(BaseModel):
    """
    One attacker interaction, normalized the same way regardless of which
    honeypot produced it. This is what the Agent publishes over MQTT and
    what the Controller's Event Ingestion endpoint/WebSocket receives.

    Field-by-field:
      event_id      Unique ID for this event. Agent generates it (uuid4) so
                     duplicates are detectable even if a message is retried.
      node_id       Which Deception Node produced this (assigned at
                     registration, e.g. "node-ssh-01").
      service       Which honeypot type -- see Service enum.
      session_id    Groups events belonging to one attacker connection/session
                     on this node. Generated by the honeypot/Agent per session.
      source_ip     Attacker's IP as seen by the honeypot. This is the primary
                     correlation key the Threat Correlation Engine uses to link
                     events across different nodes into one campaign.
      source_port   Attacker's source port, if available. Optional.
      timestamp     UTC timestamp of the interaction (NOT when it reached the
                     Controller -- always the honeypot's own clock). Always
                     sort campaign timelines by this field, never arrival order.
      event_type    What kind of interaction -- see EventType enum.
      payload       Event-type-specific details as a free-form dict, e.g.
                     {"username": "root", "password": "admin123", "success": False}
                     for an auth_attempt, or {"command": "cat /etc/passwd"} for
                     a command event. Kept flexible on purpose -- each honeypot
                     owner decides what's useful to log for their event types.
      credential    Convenience field for username:password style attempts,
                     duplicated out of payload so the scoring engine and
                     dashboard don't have to parse payload just for this.
                     Optional -- only set when relevant (e.g. auth_attempt).
      campaign_id   Set by the Controller after correlation runs, NOT by the
                     Agent. Always None/absent on the way in from a node.
      raw_log       Optional original log line/entry, kept for debugging when
                     the normalized fields aren't enough to explain something.
    """

    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    node_id: str
    service: Service
    session_id: str
    source_ip: str
    source_port: Optional[int] = None
    timestamp: datetime
    event_type: EventType
    payload: dict[str, Any] = Field(default_factory=dict)
    credential: Optional[str] = None
    campaign_id: Optional[str] = None
    raw_log: Optional[str] = None

    # -- validation -----------------------------------------------------

    @field_validator("node_id", "session_id")
    @classmethod
    def not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("must not be blank")
        return v

    @field_validator("timestamp")
    @classmethod
    def must_be_utc(cls, v: datetime) -> datetime:
        # Every timestamp in the system is UTC. Naive datetimes are assumed
        # UTC and tagged; anything in another timezone is converted.
        if v.tzinfo is None:
            return v.replace(tzinfo=timezone.utc)
        return v.astimezone(timezone.utc)

    class Config:
        use_enum_values = True

    # -- convenience ------------------------------------------------------

    def to_json(self) -> str:
        """What the Agent actually publishes over MQTT."""
        return self.model_dump_json()

    @classmethod
    def from_json(cls, raw: str) -> "InteractionEvent":
        """What the Controller's ingestion layer parses on receipt."""
        return cls.model_validate_json(raw)


# ---------------------------------------------------------------------------
# Example / smoke test -- run this file directly to sanity-check the schema
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    example = InteractionEvent(
        node_id="node-ssh-01",
        service=Service.SSH,
        session_id="sess-8f3a",
        source_ip="100.64.0.7",
        timestamp=datetime.now(timezone.utc),
        event_type=EventType.AUTH_ATTEMPT,
        payload={"username": "root", "password": "admin123", "success": False},
        credential="root:admin123",
    )

    encoded = example.to_json()
    print("Serialized (what the Agent publishes):")
    print(encoded)

    decoded = InteractionEvent.from_json(encoded)
    print("\nRound-tripped back (what the Controller receives):")
    print(decoded)

    assert decoded == example
    print("\nOK: schema round-trips cleanly.")